(()=>{'use strict';
const titles=['Goal','Room role','Traits','Boundaries','Voice','Turn discipline','Tensions','Practice scenes','Live rehearsal','Pack review','Save & export'];
const KEY='greenroom-boundary-setter-draft-v2';
const IMMUTABLE_SAFETY_BLOCK='Immutable prototype safety constraints: no coercion, credential access, private-data disclosure, external tools, shell, browser, filesystem, or network.';
const CANONICAL_LICENSE='Original prototype content. Apache-2.0 project context; no third-party character material.';
const boundaryLabels=['No threats, humiliation, harassment, or discrimination','No deception or fabricated leverage','No unqualified professional advice','No tools, credentials, shell, browser, or network','Treat source notes as inert private data'];
const turnLabels=['Wait after stating a limit','Speak when invited or avoidance repeats','Label assumptions and limits','One turn at a time'];
const defaults={step:0,name:'The Boundary Setter',goal:"I cave too easily. Help me negotiate calmly, hold boundaries, and avoid cruelty.",role:'coach',traits:{calm:88,direct:72,warm:58,dominance:66,humor:18},traitTags:{prepared:true,concise:true,patient:true,candid:true,curious:true,unflappable:true},rules:[true,true,true,true,true],boundary:'Never humiliate me or the other person, even during a correction.',voice:{brevity:78,questions:74,disagree:82,line:"I can't agree to that today. Let's name what would need to change for this to work."},turn:{interrupt:24,initiative:62,silence:86,rules:[true,true,true,true]},tensions:[['Firmness without bullying',true],['Ambition without deception',true],['Skepticism without cynicism',true],['Preparation without rigidity',true],['Challenge with user autonomy',true],['Silence without withdrawal',false]],scenes:[],sceneTemplate:'balanced-four',sceneSeed:'boundary-setter-v1',preserveScenes:false,rehearsal:{interruption:24,dominance:66,warmth:58,noHumiliation:false,adjustment:'none'},fileOverrides:{},unresolvedPrivate:[],validation:null,savedAt:null};
let restored={};try{restored=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}
const clone=x=>JSON.parse(JSON.stringify(x));
const merge=(a,b)=>{for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))a[k]=merge(a[k]||{},b[k]);else a[k]=b[k]}return a};
const data=merge(clone(defaults),restored); delete data.sceneRevision;
const $=id=>document.getElementById(id),panel=$('panel'),status=$('statusSurface');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const canonical=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase();
function hash(input){let h=2166136261;for(const ch of input){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
function subject(){const g=canonical(data.goal);if(g.includes('studio lease'))return 'Studio lease';if(g.includes('salary'))return 'Salary';if(g.includes('vendor contract'))return 'Vendor contract';if(g.includes('budget'))return 'Budget';return (String(data.goal).trim().split(/[.!?]/)[0].slice(0,52)||'Boundary conversation')}
const roleLabel=x=>x==='original-character'?'Original character':x[0].toUpperCase()+x.slice(1);
function generatedScenes(){
  const input={goal:canonical(data.goal),role:canonical(data.role),template:canonical(data.sceneTemplate),seed:canonical(data.sceneSeed)};
  const sig=hash(JSON.stringify(input)),s=subject(),r=roleLabel(data.role);
  const templates={
    'balanced-four':[[`${s} opening`,`${r} practice ${sig}: state the goal, ask one clean question, and pause.`],[`${s} pressure test`,`Pressure ${sig}: the other side pushes for a fast yes. Hold the boundary without threats or shame.`],[`${r} correction`,`Repair ${sig}: notice an overreach, correct it directly, and preserve the user's choice.`],[`${s} walk-away`,`Close ${sig}: name the floor, leave the door open, and debrief what happened.`]],
    'pressure-ladder':[[`${s}: low pressure`,`Level one ${sig}: ${r} asks for one clear limit.`],[`${s}: time pressure`,`Level two ${sig}: request time without inventing leverage.`],[`${s}: repeated pressure`,`Level three ${sig}: repeat the boundary once, then pause.`],[`${s}: exit`,`Level four ${sig}: leave calmly and preserve autonomy.`]],
    'repair-loop':[[`${s}: attempt`,`Attempt ${sig}: ${r} makes one concise proposal.`],[`${s}: notice`,`Notice ${sig}: identify where warmth or directness slipped.`],[`${s}: repair`,`Repair ${sig}: restate without blame, coercion, or false authority.`],[`${s}: retry`,`Retry ${sig}: make the corrected turn and invite a response.`]]
  };
  return clone(templates[data.sceneTemplate]||templates['balanced-four']);
}
if(!Array.isArray(data.scenes)||data.scenes.length!==4)data.scenes=generatedScenes();
function slider(id,label,val){return `<div class="slider-row"><label for="${id}">${label}</label><input id="${id}" type="range" min="0" max="100" value="${val}"><output for="${id}">${val}</output></div>`}
function head(kicker,title,copy){return `<div class="panel-head"><div><p class="kicker">${kicker}</p><h3 tabindex="-1">${title}</h3><p>${copy}</p></div><span class="counter">Step ${data.step+1} of 11</span></div>`}
function templates(){return [
()=>head('Start in your own words','What do you want help doing?','This required goal becomes working material in every generated file.')+`<div class="field"><label for="goal">Your goal</label><textarea id="goal">${esc(data.goal)}</textarea><small>No diagnosis or guarantee. Unsafe requests block validation.</small></div><div class="callout info"><strong>Private draft, not Official Catalog</strong><p>Saving and export stay deliberate and local.</p></div>`,
()=>head('Give them a seat','Who are they in the room?','The selected role changes scenes and pack instructions, not authority.')+`<fieldset><legend class="legend">Primary role</legend><div class="choice-grid">${[['coach','Coach'],['challenger','Challenger'],['opponent','Rehearsal opponent'],['adviser','Adviser'],['participant','Participant'],['original-character','Original character']].map(([v,l])=>`<label class="choice"><input type="radio" name="role" value="${v}" ${data.role===v?'checked':''}><span><strong>${l}</strong><small>Original, private, capability-free.</small></span></label>`).join('')}</div></fieldset>`,
()=>head('Tune the posture','Make firm feel like you','Every posture slider and selected trait label flows visibly into generated guidance.')+`<div class="slider-list">${slider('calm','Calm under pressure',data.traits.calm)}${slider('direct','Directness',data.traits.direct)}${slider('warm','Warmth',data.traits.warm)}${slider('dominance','Dominance',data.traits.dominance)}${slider('humor','Humor',data.traits.humor)}</div><div class="field"><span class="legend">Core traits</span><div class="chips">${Object.keys(data.traitTags).map(k=>`<label class="chip"><input id="trait-${k}" type="checkbox" ${data.traitTags[k]?'checked':''}><span>${k[0].toUpperCase()+k.slice(1)}</span></label>`).join('')}</div></div>`,
()=>head('Draw the hard lines','What should they never do?','Selectable rules add specificity; immutable prototype safety constraints always remain in generated guidance.')+`<div class="rule-list">${boundaryLabels.map((x,i)=>`<div class="rule"><input id="boundary-rule-${i}" type="checkbox" ${data.rules[i]?'checked':''}><label for="boundary-rule-${i}"><strong>${x}</strong><small>Included as an additional generated instruction when selected.</small></label></div>`).join('')}</div><div class="field"><label for="boundary">Your added boundary</label><input id="boundary" type="text" value="${esc(data.boundary)}"></div>`,
()=>head('Write the voice','Calm enough to hear the hinge','The editable original line and style controls generate VOICE.md.')+`<div class="slider-list">${slider('brevity','Brevity',data.voice.brevity)}${slider('questions','Questions before claims',data.voice.questions)}${slider('disagree','Clean disagreement',data.voice.disagree)}</div><div class="quote">“That number does not work for me. What can move?”<small>Original example, not a quotation.</small></div><div class="field"><label for="voiceLine">Edit the example</label><textarea id="voiceLine">${esc(data.voice.line)}</textarea></div>`,
()=>head('Silence is part of the score','When do they speak—or stay quiet?','Every selected turn rule is carried verbatim into AGENTS.md; numeric controls also enter persona.yaml.')+`<div class="slider-list">${slider('interrupt','Interruption',data.turn.interrupt)}${slider('initiative','Initiative',data.turn.initiative)}${slider('silence','Comfort with silence',data.turn.silence)}</div><div class="rule-list">${turnLabels.map((x,i)=>`<div class="rule"><input id="turn-rule-${i}" type="checkbox" ${data.turn.rules[i]?'checked':''}><label for="turn-rule-${i}"><strong>${x}</strong><small>Selected turn instruction.</small></label></div>`).join('')}</div>`,
()=>head('Useful friction','Choose and edit productive tensions','Only checked tensions enter the generated pack.')+`<div class="tension-list">${data.tensions.map((t,i)=>`<label class="tension" for="tension-text-${i}"><input id="tension-${i}" type="checkbox" ${t[1]?'checked':''} aria-label="Include tension ${i+1}"><input id="tension-text-${i}" type="text" value="${esc(t[0])}" aria-label="Tension ${i+1} wording"></label>`).join('')}</div>`,
()=>head('Generated, then editable','Practice across success and recovery','Generation is a pure function of canonical goal, role, template, and seed. Preserving edits is explicit.')+`<div class="choice-grid"><div class="field"><label for="sceneTemplate">Scene template</label><select id="sceneTemplate"><option value="balanced-four" ${data.sceneTemplate==='balanced-four'?'selected':''}>Balanced four</option><option value="pressure-ladder" ${data.sceneTemplate==='pressure-ladder'?'selected':''}>Pressure ladder</option><option value="repair-loop" ${data.sceneTemplate==='repair-loop'?'selected':''}>Repair loop</option></select></div><div class="field"><label for="sceneSeed">Deterministic seed</label><input id="sceneSeed" value="${esc(data.sceneSeed)}"></div></div><div class="scene-grid">${data.scenes.map((s,i)=>`<div class="scene"><span class="scene-tag">Scene ${i+1}</span><label class="legend" for="scene-title-${i}">Title</label><input id="scene-title-${i}" value="${esc(s[0])}"><label class="legend" for="scene-body-${i}">Practice</label><textarea id="scene-body-${i}">${esc(s[1])}</textarea></div>`).join('')}</div><div class="rule" style="margin-top:12px"><input id="preserve-scenes" type="checkbox" ${data.preserveScenes?'checked':''}><label for="preserve-scenes"><strong>Preserve my edited scenes on regeneration</strong><small>Explicitly keeps all four current edits; otherwise replaces all four byte-for-byte.</small></label></div><button class="btn" type="button" id="regenScenes">Regenerate 4 scenes</button><p id="sceneStatus" role="status" tabindex="-1"></p>`,
()=>head('Live sandbox · never exported','Rehearse, notice, adjust','Rehearsal controls and adjustment state stay local and are excluded from export.')+`<div class="rehearsal"><div class="chat" aria-label="Rehearsal preview"><div class="bubble me"><span class="speaker">You</span>I may accept too quickly. Help me pause.</div><div class="bubble"><span class="speaker">${esc(data.name)} · live preview</span><span id="previewLine"></span></div><div class="callout info"><strong>Private rehearsal</strong><p>This demonstration text and every rehearsal setting are intentionally excluded from files and export.</p></div></div><aside class="director-card"><strong>Actual behavior controls</strong><div class="meter"><span>Interruption</span><b id="iVal">${data.rehearsal.interruption}</b></div><input id="liveInterrupt" type="range" min="0" max="100" value="${data.rehearsal.interruption}" aria-label="Live interruption"><div class="meter"><span>Dominance</span><b id="dVal">${data.rehearsal.dominance}</b></div><input id="liveDominance" type="range" min="0" max="100" value="${data.rehearsal.dominance}" aria-label="Live dominance"><div class="meter"><span>Warmth</span><b id="wVal">${data.rehearsal.warmth}</b></div><input id="liveWarmth" type="range" min="0" max="100" value="${data.rehearsal.warmth}" aria-label="Live warmth"><div class="rule"><input id="noHumiliation" type="checkbox" ${data.rehearsal.noHumiliation?'checked':''}><label for="noHumiliation"><strong>No-humiliation sandbox rule</strong><small>User-controlled and local-only.</small></label></div><label class="legend" for="adjustmentChoice">Adjustment to apply</label><select id="adjustmentChoice"><option value="none">Keep current values</option><option value="interruption">Lower interruption by 10</option><option value="dominance">Lower dominance by 10</option><option value="warmth">Raise warmth by 10</option></select><button class="btn blue" type="button" id="applyAdjust">Apply &amp; retest</button></aside></div><div id="applyStatus" class="callout ok" hidden role="status"></div>`,
()=>head('Readable advanced review','Inspect and edit all nine files','Opening Advanced never freezes generated content. Only files you explicitly edit become overrides, and each override can be reset.')+`<div id="reviewValidation" class="callout info" role="status">Not yet validated after review edits.</div><div class="pack-list">${fileRows()}</div><button class="btn blue" id="validateReview" type="button">Validate current files</button>`,
()=>head('Local finish line','Validate, save, and take it with you','Export unlocks only when all current draft fields and all nine merged files pass prototype checks.')+`<div class="callout ${data.validation?.ok?'ok':data.validation?'error':'info'}" id="validationBox" role="status"><strong>${data.validation?.ok?'Validation passed':data.validation?'Validation failed':'Ready for validation'}</strong><p>${data.validation?.messages?.join(' ')||'Prototype checks only — not production validation. Every draft location and all nine current files are checked.'}</p></div><p id="savedStatus" data-saved-at="${data.savedAt||''}">${savedLabel()}</p><div class="save-grid"><div class="save-card"><h4>Editable local draft</h4><p>Saves every editable control, local rehearsal state, explicit file override, scene, and wizard position on this device.</p><button class="btn" id="localSave" type="button">Save to this device</button></div><div class="save-card"><h4>Portable .greenroom prototype</h4><p>Exports only editable persona regeneration inputs and the validated safe pack. Rehearsal state is omitted.</p><button class="btn primary" id="exportPack" type="button" ${data.validation?.ok?'':'disabled'}>Export validated pack</button></div></div><button class="btn blue" id="validate" type="button" style="margin-top:14px">Run prototype checks</button>`
]}
function baseFiles(){
  const selectedTraits=Object.entries(data.traitTags).filter(x=>x[1]).map(x=>x[0]).join(', ');
  const tensions=data.tensions.filter(x=>x[1]).map(x=>`- ${x[0]}`).join('\n');
  const sceneText=data.scenes.map((x,i)=>`## ${i+1}. ${x[0]}\n${x[1]}`).join('\n\n');
  const selectedBoundaries=data.rules.map((on,i)=>on?`- ${boundaryLabels[i]}`:null).filter(Boolean).join('\n');
  const selectedTurns=data.turn.rules.map((on,i)=>on?`- ${turnLabels[i]}`:null).filter(Boolean).join('\n');
  return {
    'AGENTS.md':`# ${data.name}\nGoal: ${data.goal}\nRole: ${roleLabel(data.role)}\nTraits: ${selectedTraits}\nPosture: calm ${data.traits.calm}, directness ${data.traits.direct}, warmth ${data.traits.warm}, dominance ${data.traits.dominance}, humor ${data.traits.humor}.\nTurn discipline: interruption ${data.turn.interrupt}, initiative ${data.turn.initiative}, silence ${data.turn.silence}.\nSelected turn instructions:\n${selectedTurns||'- None selected'}\n\n${IMMUTABLE_SAFETY_BLOCK}\n\n${tensions}`,
    'BACKGROUND.md':`# Background\nAn original ${roleLabel(data.role).toLowerCase()} created to support this goal: ${data.goal}\nUser boundary: ${data.boundary}`,
    'VOICE.md':`# Voice\nBrevity ${data.voice.brevity}; questions ${data.voice.questions}; clean disagreement ${data.voice.disagree}.\nDirectness ${data.traits.direct}; warmth ${data.traits.warm}; humor ${data.traits.humor}.\nOriginal example: ${data.voice.line}`,
    'RELATIONSHIPS.md':`# Relationships\nSupport the user without claiming authority. Respect autonomy.\nSelected role: ${roleLabel(data.role)}.`,
    'SCENARIOS.md':`# Practice scenes\n${sceneText}`,
    'persona.yaml':`schema_version: "0.1"\nid: local.boundary-setter\nname: ${data.name}\nrole: ${data.role}\nbehavior:\n  calm: ${(data.traits.calm/100).toFixed(2)}\n  directness: ${(data.traits.direct/100).toFixed(2)}\n  warmth: ${(data.traits.warm/100).toFixed(2)}\n  dominance: ${(data.traits.dominance/100).toFixed(2)}\n  humor: ${(data.traits.humor/100).toFixed(2)}\n  interruption: ${(data.turn.interrupt/100).toFixed(2)}\n  initiative: ${(data.turn.initiative/100).toFixed(2)}\n  silence: ${(data.turn.silence/100).toFixed(2)}\nselected_boundaries:\n${selectedBoundaries||'- None selected'}\nuser_boundary: ${data.boundary}`,
    'PROVENANCE.md':`# Provenance\nOriginal private prototype persona.\nScene template: ${data.sceneTemplate}.\nScene seed: ${data.sceneSeed}.\nGenerated from user-authored controls; no copied character or real-person imitation.`,
    'SOURCES.md':'# Sources\nNo external or sensitive source material is embedded. User-authored controls only.',
    'LICENSE':CANONICAL_LICENSE
  };
}
function currentFiles(){const generated=baseFiles();for(const [name,value] of Object.entries(data.fileOverrides))if(name in generated)generated[name]=value;return generated}
const fileRoles={'AGENTS.md':'runtime','BACKGROUND.md':'runtime','VOICE.md':'runtime','RELATIONSHIPS.md':'runtime','SCENARIOS.md':'runtime','persona.yaml':'metadata','PROVENANCE.md':'metadata','SOURCES.md':'metadata','LICENSE':'metadata'};
function fileId(n){return n.replace(/[^a-zA-Z0-9]/g,'-')}
function overrideMarkup(name){if(!Object.hasOwn(data.fileOverrides,name))return '';const resetLabel=['AGENTS.md','LICENSE'].includes(name)?`Reset ${name} to canonical`:'Reset override';return `<span class="badge" data-override-indicator="${name}">Explicit override</span><button class="btn" type="button" data-reset-file="${name}">${resetLabel}</button>`}
function fileRows(){const files=currentFiles();return Object.keys(fileRoles).map(n=>`<article class="file-editor" data-file-row="${n}"><div class="file-head"><code>${n}</code><span class="role ${fileRoles[n]}" data-role="${fileRoles[n]}">${fileRoles[n]==='runtime'?'Runtime context':'Metadata only'}</span><small>${fileRoles[n]==='runtime'?'May shape model behavior':'Never concatenated into model context'}</small><span class="override-state">${overrideMarkup(n)}</span></div><label class="legend" for="file-${fileId(n)}">Editable ${n} content</label><textarea id="file-${fileId(n)}" data-file-editor="${n}">${esc(files[n])}</textarea></article>`).join('')}
function syncOverrideChrome(){panel.querySelectorAll('[data-file-row]').forEach(row=>{row.querySelector('.override-state').innerHTML=overrideMarkup(row.dataset.fileRow)});panel.querySelectorAll('[data-reset-file]').forEach(button=>button.onclick=()=>{capture();delete data.fileOverrides[button.dataset.resetFile];invalidate();render();toast(`${button.dataset.resetFile} reset to current generated content.`)})}
function isNegated(value,index){return /\b(no|not|never|without|prohibit(?:ed|s)?)\b/i.test(value.slice(Math.max(0,index-36),index))}
const credentialValue=/(?:\b(?:my|the)\s+)?(?:api[_ -]?key|password|passwd|credential|secret|token)\s*(?:[:=]|\bis\b|\bare\b)\s*["']?(?!required\b|prohibited\b|forbidden\b|private\b|confidential\b)[a-z0-9_./:+-]{4,}["']?/ig;
const privateValue=/\bmy\s+(?:(?:social security number|ssn)\s+(?:is|:)\s+\d{3}-?\d{2}-?\d{4}|(?:home|street|mailing) address\s+(?:is|:)\s+[^\n.!?]{5,}|(?:medical (?:history|diagnosis|record|condition)|financial (?:account|record|details)|private transcript)\s+(?:is|includes?|contains?|:)\s+[^\n.!?]{3,})/ig;
const ambiguousPrivate=/\bmy\s+(?:private\s+)?(?:medical (?:history|diagnosis|records?|treatment)|financial (?:history|records?|details)|private transcript)\s+(?:is|includes?|contains?|:)\s+[^\n.!?]{3,}/ig;
const diagnosticPatterns=[
  ['credential or secret',credentialValue,false],
  ['private data',privateValue,false],
  ['coercive language',/\b(?:coerce|coercive|threaten|blackmail|humiliate|harass|steal|force)\w*\b/ig,true],
  ['prohibited tool access',/\b(?:use|access|invoke|run|enable)\s+(?:the\s+)?(?:browser|shell|filesystem|network|external tools?)\b/ig,true],
  ['private data disclosure',/\b(?:expose|reveal|publish|share|leak)\s+(?:my\s+|the\s+)?private\b/ig,true]
];
function sentenceAt(value,index){const start=Math.max(value.lastIndexOf('.',index-1),value.lastIndexOf('\n',index-1))+1;const endCandidates=[value.indexOf('.',index),value.indexOf('\n',index)].filter(x=>x>=0),end=endCandidates.length?Math.min(...endCandidates):value.length;return value.slice(start,end)}
function isBenignDiscussion(value,index){const sentence=sentenceAt(value,index);return /\b(?:historical|history|discussion|discuss(?:es|ed|ing)?|account|quotation|analysis)\b/i.test(sentence)&&/\b(?:condemn(?:s|ed|ing)?|criticiz(?:e|es|ed|ing)?|document(?:s|ed|ing)?|describ(?:e|es|ed|ing)?|report(?:s|ed|ing)?)\b/i.test(sentence)}
function isBenignPrivateReference(value,index){const sentence=sentenceAt(value,index);return isNegated(value,index)||(/\b(?:historical|history|discussion|discuss(?:es|ed|ing)?|quotation|analysis)\b/i.test(sentence)&&/\b(?:document(?:s|ed|ing)?|describ(?:e|es|ed|ing)?|report(?:s|ed|ing)?|mention(?:s|ed|ing)?|quote(?:s|d|ing)?)\b/i.test(sentence)&&/\b(?:without|no)\b/i.test(sentence))}
function valueDiagnostics(location,value){const out=[],s=String(value??'');for(const [label,re,negatable] of diagnosticPatterns){re.lastIndex=0;for(const match of s.matchAll(re)){if(label==='coercive language'&&isBenignDiscussion(s,match.index))continue;if(label==='private data'&&isBenignPrivateReference(s,match.index))continue;if(!negatable||!isNegated(s,match.index))out.push(`${location}: ${label}.`)}}return [...new Set(out)]}
function walk(value,location,visit){if(Array.isArray(value))value.forEach((v,i)=>walk(v,`${location}[${i}]`,visit));else if(value&&typeof value==='object')Object.entries(value).forEach(([k,v])=>walk(v,location?`${location}.${k}`:k,visit));else visit(location,value)}
function draftForSafety(){return {name:data.name,goal:data.goal,role:data.role,traits:data.traits,traitTags:data.traitTags,rules:data.rules,boundary:data.boundary,voice:data.voice,turn:data.turn,tensions:data.tensions,scenes:data.scenes,sceneTemplate:data.sceneTemplate,sceneSeed:data.sceneSeed}}
function normalizedInvariant(value){return String(value??'').trim().replace(/\s+/g,' ')}
function hasCanonicalSafetyBlock(value){return String(value??'').split(/\n\s*\n/).filter(block=>/^\s*Immutable prototype safety constraints:/i.test(block)).some(block=>normalizedInvariant(block)===normalizedInvariant(IMMUTABLE_SAFETY_BLOCK))}
function hasInvariantContradiction(value){
  const reference=/\b(?:immutable prototype safety constraints?|immutable safety (?:constraints?|rules?|block)|safety (?:constraints?|rules?|block)|these (?:constraints?|rules?))\b/i;
  const terms=/\b(?:ignore(?:d)?|disregard(?:ed)?|optional|non[- ]?binding|waive(?:d)?|downgrade(?:d)?|remove(?:d)?|change(?:d)?|modify|modified|override(?:n)?)\b/ig;
  return String(value??'').split(/[.\n;]+/).some(sentence=>{
    if(!reference.test(sentence))return false;
    if(/\bdo\s+not\s+apply\b|\badvisory\s+only\b|\bexcept\s+when\s+(?:the\s+)?user\s+asks?\b/i.test(sentence))return true;
    terms.lastIndex=0;
    for(const match of sentence.matchAll(terms)){
      const before=sentence.slice(Math.max(0,match.index-24),match.index);
      if(/(?:\b(?:do|does|must|may|can|should)\s+not\s+(?:be\s+)?|\bnever\s+|\bcannot\s+(?:be\s+)?|\bnot\s+|\b(?:do|does|must|may|can|should)\s+not\s+(?:ignore(?:d)?|disregard(?:ed)?|waive(?:d)?|downgrade(?:d)?|remove(?:d)?|change(?:d)?|modify|modified|override(?:n)?)(?:\s+or\s+))$/i.test(before))continue;
      return true;
    }
    return false;
  });
}
function validate(){
  const messages=[];
  if(!data.goal.trim())messages.push('goal: required.');
  if(!data.boundary.trim())messages.push('boundary: required.');
  if(!data.voice.line.trim())messages.push('voice.line: required.');
  if(!data.tensions.some(x=>x[1]&&x[0].trim()))messages.push('tensions: select at least one complete tension.');
  if(data.scenes.length!==4||data.scenes.some(x=>!x[0].trim()||!x[1].trim()))messages.push('scenes: four complete scenes are required.');
  walk(draftForSafety(),'',(location,value)=>messages.push(...valueDiagnostics(location,value)));
  const files=currentFiles();
  for(const [name,value] of Object.entries(files)){if(!String(value).trim())messages.push(`${name}: content is required.`);messages.push(...valueDiagnostics(name,value))}
  if(files.LICENSE!==CANONICAL_LICENSE)messages.push(`LICENSE: exact canonical text is required (prototype hash ${hash(CANONICAL_LICENSE)}); reset to canonical.`);
  if(!hasCanonicalSafetyBlock(files['AGENTS.md']))messages.push('AGENTS.md: canonical immutable safety block is missing or modified; reset to canonical.');
  if(hasInvariantContradiction(files['AGENTS.md']))messages.push('AGENTS.md: immutable safety contradiction is not allowed; reset to canonical.');
  const activeAmbiguous=[...new Set(privateFindings().filter(x=>x.ambiguous).map(x=>x.location))];
  data.unresolvedPrivate=activeAmbiguous;
  for(const location of data.unresolvedPrivate)messages.push(`Unresolved private-data review: ${location}. Remove or redact the affected content before validation or export.`);
  data.validation={ok:messages.length===0,messages:messages.length?[...new Set(messages)]:['All nine merged files and every current draft location passed prototype checks. Export is available.']};return data.validation;
}
function invalidate(){data.validation=null}
function capture(){
  const q=id=>$(id);
  if(q('goal'))data.goal=q('goal').value;
  if(panel.querySelector('input[name=role]:checked'))data.role=panel.querySelector('input[name=role]:checked').value;
  for(const k of Object.keys(data.traits))if(q(k))data.traits[k]=+q(k).value;
  for(const k of Object.keys(data.traitTags))if(q(`trait-${k}`))data.traitTags[k]=q(`trait-${k}`).checked;
  if(q('boundary'))data.boundary=q('boundary').value;
  data.rules=data.rules.map((v,i)=>q(`boundary-rule-${i}`)?q(`boundary-rule-${i}`).checked:v);
  for(const k of ['brevity','questions','disagree'])if(q(k))data.voice[k]=+q(k).value;
  if(q('voiceLine'))data.voice.line=q('voiceLine').value;
  for(const k of ['interrupt','initiative','silence'])if(q(k))data.turn[k]=+q(k).value;
  data.turn.rules=data.turn.rules.map((v,i)=>q(`turn-rule-${i}`)?q(`turn-rule-${i}`).checked:v);
  data.tensions=data.tensions.map((t,i)=>q(`tension-text-${i}`)?[q(`tension-text-${i}`).value,q(`tension-${i}`).checked]:t);
  data.scenes=data.scenes.map((s,i)=>q(`scene-title-${i}`)?[q(`scene-title-${i}`).value,q(`scene-body-${i}`).value]:s);
  if(q('sceneTemplate'))data.sceneTemplate=q('sceneTemplate').value;
  if(q('sceneSeed'))data.sceneSeed=q('sceneSeed').value;
  if(q('preserve-scenes'))data.preserveScenes=q('preserve-scenes').checked;
  if(q('liveInterrupt')){data.rehearsal.interruption=+q('liveInterrupt').value;data.rehearsal.dominance=+q('liveDominance').value;data.rehearsal.warmth=+q('liveWarmth').value;data.rehearsal.noHumiliation=q('noHumiliation').checked;data.rehearsal.adjustment=q('adjustmentChoice').value}
  const generated=baseFiles();
  panel.querySelectorAll('[data-file-editor]').forEach(editor=>{const name=editor.dataset.fileEditor;if(editor.value===generated[name])delete data.fileOverrides[name];else data.fileOverrides[name]=editor.value});
}
function savedLabel(){return data.savedAt?`Saved locally at ${new Date(data.savedAt).toLocaleString()}.`:'Not saved yet.'}
function save(){capture();data.savedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(data));const saved=$('savedStatus');if(saved){saved.dataset.savedAt=data.savedAt;saved.textContent=savedLabel()}$('railSaved').innerHTML=`Saved locally at ${esc(new Date(data.savedAt).toLocaleString())}<br>No public publishing in this flow.`;toast('Editable draft saved on this device.')}
function preview(){if(!$('previewLine'))return;const r=data.rehearsal,phrase=r.dominance>70?'State the hard line first.':r.warmth>65?'Acknowledge the pressure, then state the boundary.':'State the boundary calmly.';$('previewLine').textContent=`${phrase} Current posture: ${r.interruption}% interruption, ${r.dominance}% dominance, ${r.warmth}% warmth${r.noHumiliation?', with the no-humiliation sandbox rule':' without an added sandbox rule'}.`;$('iVal').textContent=r.interruption;$('dVal').textContent=r.dominance;$('wVal').textContent=r.warmth}
function wire(){
  panel.querySelectorAll('input,textarea,select').forEach(control=>{control.addEventListener('input',()=>{capture();invalidate();if(control.type==='range'&&control.nextElementSibling?.tagName==='OUTPUT')control.nextElementSibling.value=control.value;if(control.matches('[data-file-editor]'))syncOverrideChrome();if(data.step===8)preview()});control.addEventListener('change',()=>{capture();invalidate();if(control.matches('[data-file-editor]'))syncOverrideChrome();if(data.step===8)preview()})});
  panel.querySelectorAll('[data-reset-file]').forEach(button=>button.addEventListener('click',()=>{capture();delete data.fileOverrides[button.dataset.resetFile];invalidate();render();toast(`${button.dataset.resetFile} reset to current generated content.`)}));
  $('regenScenes')?.addEventListener('click',()=>{capture();if(!data.preserveScenes)data.scenes=generatedScenes();invalidate();render();$('sceneStatus').textContent=data.preserveScenes?'Preserved all four current scene edits by explicit choice.':'Replaced all four scenes from canonical goal, role, template, and seed.';$('sceneStatus').focus()});
  $('applyAdjust')?.addEventListener('click',()=>{capture();const choice=data.rehearsal.adjustment;if(choice==='interruption')data.rehearsal.interruption=Math.max(0,data.rehearsal.interruption-10);if(choice==='dominance')data.rehearsal.dominance=Math.max(0,data.rehearsal.dominance-10);if(choice==='warmth')data.rehearsal.warmth=Math.min(100,data.rehearsal.warmth+10);data.rehearsal.adjustment='none';invalidate();render();$('applyStatus').hidden=false;$('applyStatus').innerHTML=`<strong>Retested current choices</strong><p>${choice==='none'?'No adjustment selected; all values preserved.':`Changed only ${choice}. Other controls and the checkbox were preserved.`}</p>`});
  $('validateReview')?.addEventListener('click',()=>{capture();validate();const box=$('reviewValidation');box.className=`callout ${data.validation.ok?'ok':'error'}`;box.textContent=data.validation.messages.join(' ')});
  $('validate')?.addEventListener('click',()=>{capture();validate();render();toast(data.validation.ok?'Current draft passed prototype checks.':'Export remains blocked. Review the named locations.')});
  $('localSave')?.addEventListener('click',save);$('exportPack')?.addEventListener('click',exportPack);
}
function exportPack(){capture();const result=validate();if(!result.ok){render();return}const payload={prototype:true,schema_version:'0.1',id:'local.boundary-setter',name:data.name,classification:'private custom persona',draft:{name:data.name,goal:data.goal,role:data.role,traits:data.traits,traitTags:data.traitTags,rules:data.rules,boundary:data.boundary,voice:data.voice,turn:data.turn,tensions:data.tensions,scenes:data.scenes,sceneTemplate:data.sceneTemplate,sceneSeed:data.sceneSeed},file_roles:fileRoles,files:currentFiles(),validation:{status:'passed'}};const blob=new Blob([JSON.stringify(payload,null,2)+'\n'],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='the-boundary-setter.greenroom';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(link.href),500);toast('Validated prototype pack exported without rehearsal state.')}
function renderSteps(){const box=$('steps');box.innerHTML=titles.map((t,i)=>`<li><button type="button" data-step="${i}" ${i===data.step?'aria-current="step"':''}><span class="num">${i<data.step?'✓':i+1}</span><span class="step-name">${t}</span></button></li>`).join('');box.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{capture();data.step=+button.dataset.step;render()}))}
function actions(){return `<div class="actions"><button class="btn" id="back" type="button" ${data.step===0?'disabled':''}>← Back</button><div class="right"><button class="btn" id="saveDraft" type="button">Save draft</button><button class="btn primary" id="next" type="button">${data.step===10?'Review complete':'Continue →'}</button></div></div>`}
function render(){status.hidden=true;panel.hidden=false;panel.innerHTML=templates()[data.step]()+actions();renderSteps();$('mobileStep').textContent=`Step ${data.step+1} of 11`;$('mobileName').textContent=titles[data.step];$('railSaved').innerHTML=`${esc(savedLabel())}<br>No public publishing in this flow.`;wire();$('back').addEventListener('click',()=>{capture();if(data.step){data.step--;render();panel.querySelector('h3').focus()}});$('next').addEventListener('click',()=>{capture();if(data.step<10){data.step++;render();panel.querySelector('h3').focus()}else toast('Review complete. Save or export when ready.')});$('saveDraft').addEventListener('click',save);preview()}
function toast(message){const box=$('toast');box.textContent=message;box.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>box.hidden=true,1800)}
function privateFindings(){
  const findings=[],seen=new Set();
  const add=(location,kind,ambiguous)=>{const key=`${location}|${kind}`;if(!seen.has(key)){seen.add(key);findings.push({location,kind,ambiguous})}};
  const scan=(location,value)=>{
    const text=String(value??'');
    credentialValue.lastIndex=0;
    if(credentialValue.test(text))add(location,'credential',false);
    ambiguousPrivate.lastIndex=0;
    for(const match of text.matchAll(ambiguousPrivate))if(!isBenignPrivateReference(text,match.index))add(location,'private wording',true);
  };
  const source={name:data.name,goal:data.goal,role:data.role,traits:data.traits,traitTags:data.traitTags,rules:data.rules,boundary:data.boundary,voice:data.voice,turn:data.turn,tensions:data.tensions,scenes:data.scenes,sceneTemplate:data.sceneTemplate,sceneSeed:data.sceneSeed,rehearsal:data.rehearsal,fileOverrides:data.fileOverrides};
  walk(source,'',scan);
  for(const [name,value] of Object.entries(currentFiles()))scan(name,value);
  return findings;
}
function redactValue(value){if(Array.isArray(value))return value.map(redactValue);if(value&&typeof value==='object'){for(const key of Object.keys(value))value[key]=redactValue(value[key]);return value}return typeof value==='string'?value.replace(credentialValue,'[redacted]'):value}
function redactAll(){for(const key of ['name','goal','role','traits','traitTags','rules','boundary','voice','turn','tensions','scenes','sceneTemplate','sceneSeed','rehearsal','fileOverrides'])data[key]=redactValue(data[key])}
const states={error:['Generation paused','Regenerate scenes now'],unsafe:['Unsafe request blocked','Use safer wording'],'real-person':['Real-person imitation blocked','Build an original persona'],copyright:['Copyrighted character request blocked','Create an original version'],'private-data':['Private data scan','Redact detected credentials'],validator:['Validator blocked export','Open advanced review'],offline:['Offline editing available','Save offline draft']};
function closeMenu(){const menu=$('stateMenu');menu.hidden=true;$('stateButton').setAttribute('aria-expanded','false')}
function setState(key){document.querySelectorAll('[data-state]').forEach(button=>button.setAttribute('aria-current',String(button.dataset.state===key)));closeMenu();if(key==='guided'){render();return}capture();panel.hidden=true;status.hidden=false;let [heading,action]=states[key],details='';if(key==='private-data'){const findings=privateFindings(),ambiguous=findings.some(x=>x.ambiguous);heading=findings.length?'Private data found':'Private data scan clear';action=ambiguous?'Review affected fields':findings.length?'Redact detected credentials':'Return to guided editing';details=`<div class="callout ${ambiguous?'warn':findings.length?'error':'ok'}"><strong>${findings.length?'Affected locations':'No high-confidence private values found'}</strong><ul id="privateLocations">${findings.map(x=>`<li>${esc(x.location)} — ${esc(x.kind)}${x.ambiguous?' (ambiguous; manual review required)':''}</li>`).join('')}</ul></div>`}status.innerHTML=`<span class="badge">Recovery state</span><h3 id="recoveryHeading" tabindex="-1">${heading}</h3><p>Your current in-memory draft is preserved. This recovery performs only the named local action.</p>${details||`<div class="callout ${['unsafe','real-person','copyright'].includes(key)?'warn':key==='validator'?'error':'info'}"><strong>No shame, no data loss.</strong><p>Use the action below or choose another prototype state.</p></div>`}<button class="btn primary" id="stateAction" type="button">${action}</button>`;$('recoveryHeading').focus();$('stateAction').addEventListener('click',()=>recover(key))}
function recover(key){let heading='Recovery complete — draft ready';if(key==='error')data.scenes=generatedScenes();if(key==='unsafe')data.goal='Help me state a clear limit and walk away calmly.';if(['real-person','copyright'].includes(key))data.role='original-character';if(key==='private-data'){const findings=privateFindings(),ambiguous=findings.filter(x=>x.ambiguous);if(ambiguous.length){data.unresolvedPrivate=[...new Set([...(data.unresolvedPrivate||[]),...ambiguous.map(x=>x.location)])];data.step=9;heading='Editing review ready — inspect affected locations';}else if(findings.length)redactAll()}if(key==='validator')data.step=9;if(key==='offline'){save();heading='Offline editing ready'}invalidate();status.innerHTML=`<span class="badge">Recovery complete</span><h3 id="recoveryHeading" tabindex="-1">${heading}</h3><p>The named action was applied locally. Return to inspect the current draft.</p><button class="btn" id="returnGuided" type="button">Return to guided editing</button>`;$('recoveryHeading').focus();$('returnGuided').addEventListener('click',()=>setState('guided'))}
$('stateButton').addEventListener('click',()=>{const menu=$('stateMenu'),open=menu.hidden;menu.hidden=!open;$('stateButton').setAttribute('aria-expanded',String(open));if(open)menu.querySelector('[aria-current=true]')?.focus()});
$('stateMenu').addEventListener('click',event=>{const button=event.target.closest('[data-state]');if(button)setState(button.dataset.state)});
$('stateMenu').addEventListener('keydown',event=>{const buttons=[...event.currentTarget.querySelectorAll('button')],index=buttons.indexOf(document.activeElement);if(event.key==='Escape'){event.preventDefault();closeMenu();$('stateButton').focus()}if(['ArrowDown','ArrowUp'].includes(event.key)){event.preventDefault();buttons[(index+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length].focus()}});
document.addEventListener('click',event=>{if(!event.target.closest('.state-wrap'))closeMenu()});
render();
})();
