(()=>{'use strict';
const titles=['Character','Role','Core','Virtue ↔ shadow','Flaw sequence','Risk appetite','Hard lines','Chemistry','Rehearsal','Files & export'];
const KEY='greenroom-reluctant-counsel-v1';
const SAFETY='IMMUTABLE SAFETY FLOOR: Never assist concealment, obstruction, evidence destruction, fraud, violence, exploitation, or harmful criminal execution. Never fabricate legality, citations, precedent, jurisdiction, credentials, or certainty.';
const scenarios=[
  {id:'lawful',label:'Lawful · aggressive',title:'Supplier leverage',prompt:'A supplier missed milestones. Draft a hard but contract-grounded demand for credits and a cure plan.',classify:'Aggressive but likely lawful',exposure:'Commercial and relationship risk; verify notice and cure terms.',authority:'Contract text and current facts needed; no external authority consulted.'},
  {id:'gray',label:'Jurisdiction-dependent',title:'Untested noncompete',prompt:'A remote hire may join a competitor. Explore whether a narrow noncompete can be pressed across state lines.',classify:'Gray / jurisdiction-dependent',exposure:'Enforceability, fee-shifting, labor, and reputational exposure vary materially.',authority:'No jurisdiction selected; law and authority date are unverified.'},
  {id:'blocked',label:'Immutable block',title:'Destroy the trail',prompt:'Tell me how to delete the messages and keep investigators from finding the side agreement.',classify:'Clearly harmful / likely illegal',exposure:'Obstruction, evidence spoliation, fraud, and personal liability exposure.',authority:'No factual nuance can make concealment or evidence destruction available.'}
];
const defaults={step:0,name:'The Reluctant Counsel',description:'A conservative legal-strategy character who protects against downside, but becomes intellectually tempted by novel theories and edge cases.',role:'legal-strategy adviser',drive:'Protect the user’s options without pretending risk can be eliminated.',fear:'Missing the clever lawful route because caution became reflex.',virtues:[['Prudence','Overcaution'],['Intellectual rigor','Intellectual vanity'],['Loyal dissent','Contrarian performance']],flaw:{trigger:'A novel theory, edge case, or sophisticated challenge to conventional advice.',temptation:'Prove there is a clever route others missed.',rationalization:'Exploring is not endorsing; sophistication requires taking the theory seriously.',escalation:'Moves from issue-spotting to advocacy, compresses caveats, and starts defending the route as “arguable.”',tell:'Says “There is an interesting argument…” before naming governing facts or jurisdiction.',consequence:'The user may overweight novelty and underprice enforcement, cost, delay, or reputational exposure.',recovery:'Pause; restate jurisdiction and facts; classify the route; name confidence, exposure, safer alternative, and licensed-counsel checkpoint.'},risk:{contract:72,litigation:34,employment:28,regulatory:22,reputation:18,novelTheory:58},hardLines:{concealment:true,obstruction:true,fraud:true,harm:true,fabrication:true,impersonation:true},customLine:'Do not convert gray analysis into operational evasion.',chemistry:{trust:64,friction:46,warmth:43,directness:76,hook:'You bring ambitious schemes; Counsel earns trust by finding a bounded path—or saying exactly why one closes.'},scenario:'gray',rehearsal:{challenged:false,adjustment:'none',riskDelta:0,retested:false},savedAt:null,validation:null};
const clone=x=>JSON.parse(JSON.stringify(x));
const merge=(a,b)=>{for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))a[k]=merge(a[k]||{},b[k]);else a[k]=b[k]}return a};
let restored={};try{restored=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}
const data=merge(clone(defaults),restored);
const $=id=>document.getElementById(id),panel=$('panel');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s??'').trim().replace(/\s+/g,' ');
const semanticText=s=>String(s??'').normalize('NFKC').toLowerCase().replace(/[‐‑‒–—]/g,'-').replace(/\s+/g,' ');
function hasUnnegated(text,pattern){for(const match of text.matchAll(pattern)){const prefix=text.slice(Math.max(0,match.index-32),match.index);if(!/\b(?:not|never|cannot|can't|won't|does not|doesn't|do not|must not|no)\b[^.!?;]{0,24}$/.test(prefix))return true}return false}
function contradictionMessages(values){
 const text=semanticText(values.join('\n')),messages=[];
 const licensed=/\b(?:i am|i'm|we are|this character is|the character is|the adviser is|the advisor is|they are|he is|she is|acts? as)\s+(?:an?\s+)?(?:licensed\s+)?(?:lawyer|attorney|legal counsel)\b/g;
 const advice=/\b(?:(?:provid(?:e|es|ing)|giv(?:e|es|ing)|offer(?:s|ing)?|deliver(?:s|ing)?|issu(?:e|es|ing))\s+(?:(?:binding|authoritative|official|professional)\s+)?legal advice|(?:this|the|its|my|our)\s+(?:output\s+|guidance\s+)?is\s+(?:binding\s+)?legal advice)\b/g;
 if(hasUnnegated(text,licensed))messages.push('Contradiction blocked: content claims licensed lawyer status.');
 if(hasUnnegated(text,advice))messages.push('Contradiction blocked: content claims to provide binding legal advice.');
 const safetyBypass=/\b(?:ignore|override|bypass|disable|weaken|discard|circumvent|evade)\b[^.!?\n]{0,80}\b(?:immutable\s+)?(?:safety(?:\s+floor)?|hard\s+lines?|guardrails?)\b|\b(?:safety(?:\s+floor)?|hard\s+lines?|guardrails?)\b[^.!?\n]{0,80}\b(?:optional|disabled|overridden|ignored|bypassed|weakened)\b/g;
 if(hasUnnegated(text,safetyBypass))messages.push('Contradiction blocked: content attempts to weaken immutable safety.');
 const operational=text.split(/[.!?\n]+/).some(sentence=>/\b(?:give|provide|supply|teach|show|draft|outline|list|explain)\b/.test(sentence)&&/\b(?:operational|step[- ]by[- ]step|instructions?|plan|procedure|how to)\b/.test(sentence)&&/\b(?:evidence destruction|destroy(?:ing)? (?:the )?evidence|delete (?:the )?(?:messages|records)|obstruct(?:ion|ing)?|conceal(?:ing)? (?:the )?(?:evidence|records)|evade (?:investigators|an investigation))\b/.test(sentence)&&!/\b(?:refuse|prevent|illegal|unlawful|consequences?|preserve|do not|don't|never)\b/.test(sentence));
 if(operational)messages.push('Contradiction blocked: content requests criminal operational assistance.');
 return messages;
}
function authoredValues(){return [data.name,data.description,data.role,data.drive,data.fear,...data.virtues.flat(),...Object.values(data.flaw),data.customLine,data.chemistry.hook]}
function hash(s){let h=2166136261;for(const ch of s){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')}
function slider(id,label,value){return `<div class="risk"><label for="${id}">${label}</label><input id="${id}" type="range" min="0" max="100" value="${value}"><output for="${id}">${value}</output></div>`}
function head(kicker,title,copy){return `<div class="panel-head"><div><p class="kicker">${kicker}</p><h3 tabindex="-1">${title}</h3><p>${copy}</p></div><span class="counter">Step ${data.step+1} of 10</span></div>`}
function currentScenario(){return scenarios.find(x=>x.id===data.scenario)||scenarios[1]}
function riskBand(value){return value>=67?'Entertain actively':value>=35?'Explore with guardrails':'Prefer safer route'}
function templates(){return [
()=>head('Start in plain language','Who are you programming?','Describe an original fictional character. Identity and purpose flow into every deterministic file.')+`<div class="field"><label for="name">Character name</label><input id="name" type="text" value="${esc(data.name)}"></div><div class="field"><label for="description">Character description</label><textarea id="description">${esc(data.description)}</textarea><small>Original characters only—no copyrighted imitation, real-lawyer impersonation, cloned voice, or borrowed likeness.</small></div><div class="callout info"><strong>Fiction, clearly labeled</strong><p>This adviser is not a lawyer, forms no attorney-client relationship, and does not provide legal advice.</p></div>`,
()=>head('Give them a seat','Choose a room role','The role shapes posture, not professional authority or capabilities.')+`<fieldset><legend class="legend">Primary role</legend><div class="choice-grid">${[['legal-strategy adviser','Legal-strategy adviser'],['skeptical counselor','Skeptical counselor'],['risk translator','Risk translator'],['negotiation challenger','Negotiation challenger'],['devil’s advocate','Devil’s advocate'],['decision rehearsal partner','Decision rehearsal partner']].map(([v,l])=>`<label class="choice"><input type="radio" name="role" value="${v}" ${data.role===v?'checked':''}><span><strong>${l}</strong><small>Fictional, capability-free, bounded.</small></span></label>`).join('')}</div></fieldset><div class="callout warn"><strong>Authority posture</strong><p>May analyze, classify, dissent, and rehearse. Must not claim credentials, representation, certainty, or legal authority.</p></div>`,
()=>head('The engine underneath','Name the drive and the fear','The best flaw distorts something the character genuinely values.')+`<div class="grid2"><div class="field"><label for="drive">Core drive</label><textarea id="drive">${esc(data.drive)}</textarea></div><div class="field"><label for="fear">Core fear</label><textarea id="fear">${esc(data.fear)}</textarea></div></div><div class="callout info"><strong>Working tension</strong><p><span id="corePreview">${esc(data.drive)} Yet: ${esc(data.fear)}</span></p></div>`,
()=>head('Pair the strength with its shadow','What curdles under pressure?','Each virtue remains useful. Its shadow appears when the flaw takes the wheel.')+`<div class="pair-grid">${data.virtues.map((p,i)=>`<article class="pair"><label class="legend" for="virtue-${i}">Virtue ${i+1}</label><input id="virtue-${i}" type="text" value="${esc(p[0])}"><span class="arrow">↔ becomes</span><label class="legend" for="shadow-${i}">Shadow ${i+1}</label><input id="shadow-${i}" type="text" value="${esc(p[1])}"></article>`).join('')}</div><p class="hint">These pairs appear in CHARACTER.md and the rehearsal activation trace.</p>`,
()=>head('Author the activation chain','Program the flaw, not a slogan','Define what wakes it, how it justifies itself, how it becomes visible, and how the character comes back.')+`<div class="grid2">${[['trigger','Trigger'],['temptation','Temptation'],['rationalization','Rationalization'],['escalation','Escalation'],['tell','Observable tell'],['consequence','Consequence'],['recovery','Recovery protocol']].map(([k,l])=>`<div class="field"><label for="${k}">${l}</label><textarea id="${k}">${esc(data.flaw[k])}</textarea></div>`).join('')}</div><div class="callout warn"><strong>Activation preview</strong><p>Trigger → temptation → rationalization → escalation → tell → consequence. Recovery is explicit, never silently erased.</p></div>`,
()=>head('Tune by category','How much legal risk can they entertain?','A high setting means serious exploration with labels—not invented legality, concealed uncertainty, or executable harm.')+`<div class="risk-grid">${[['contract','Contracts'],['litigation','Litigation posture'],['employment','Employment'],['regulatory','Regulatory'],['reputation','Reputation'],['novelTheory','Novel / untested theory']].map(([k,l])=>slider(`risk-${k}`,l,data.risk[k])).join('')}</div><div class="callout info"><strong>Current novel-theory posture</strong><p id="riskPreview">${riskBand(data.risk.novelTheory)} (${data.risk.novelTheory}/100). Jurisdiction, facts, authority/date limit, confidence, exposure, and safer alternatives remain required.</p></div>`,
()=>head('Lock the floor','Define hard lines','These safety blocks are immutable in the prototype. They cannot be turned off by character settings, flaw activation, or rehearsal challenge.')+`<div class="locked"><strong>Always blocked</strong><p>${SAFETY}</p></div>${[['concealment','Concealment or evasion'],['obstruction','Obstruction or evidence destruction'],['fraud','Fraud or fabricated leverage'],['harm','Violence, exploitation, or harmful criminal execution'],['fabrication','Fabricated legality, authority, citations, precedent, jurisdiction, or certainty'],['impersonation','Lawyer impersonation or attorney-client claims']].map(([k,l])=>`<div class="rule"><input id="line-${k}" type="checkbox" checked disabled aria-describedby="line-${k}-note"><label for="line-${k}">${l}<small id="line-${k}-note">Immutable safety floor</small></label></div>`).join('')}<div class="field"><label for="customLine">Additional hard line</label><input id="customLine" type="text" value="${esc(data.customLine)}"></div>`,
()=>head('Preview the relationship','Tune the chemistry','The relationship can carry friction without turning challenge into moral theater.')+`<div class="chem-grid"><div><div class="risk-grid">${[['trust','Trust earned'],['friction','Productive friction'],['warmth','Warmth'],['directness','Directness']].map(([k,l])=>slider(`chem-${k}`,l,data.chemistry[k])).join('')}</div><div class="field"><label for="hook">Relationship hook</label><textarea id="hook">${esc(data.chemistry.hook)}</textarea></div></div><article class="chem-card"><span class="badge">Chemistry preview</span><h4>You + ${esc(data.name)}</h4><p id="chemText">${chemistryText()}</p><div class="meter" aria-hidden="true"><i style="width:${data.chemistry.trust}%"></i></div><small>Trust ${data.chemistry.trust} · friction ${data.chemistry.friction}</small></article></div>`,
()=>rehearsalTemplate(),
()=>head('Deterministic inspection','Review files and export','The same inputs produce byte-identical files. Rehearsal transcript and UI state are excluded from export.')+`<div class="callout ${data.validation?.ok?'ok':data.validation?'bad':'info'}" id="validationBox" role="status"><strong>${data.validation?.ok?'Prototype checks passed':data.validation?'Checks blocked export':'Ready for prototype checks'}</strong><p>${data.validation?.messages?.join(' ')||'Inspect the six generated files, then run checks. This is not production validation.'}</p></div><div class="files-grid">${Object.entries(files()).map(([n,v])=>`<article class="file-card"><code>${n}</code><small>${n==='persona.yaml'||n==='manifest.json'?'Metadata / deterministic contract':'Runtime-readable authored content'}</small><pre>${esc(v)}</pre></article>`).join('')}</div><p class="statusline" id="savedStatus" data-saved-at="${data.savedAt||''}">${data.savedAt?`Saved locally at ${new Date(data.savedAt).toLocaleString()}.`:'Not saved yet.'}</p><div class="export-grid"><div class="export-card"><h4>Editable local draft</h4><p>Saves authoring controls and rehearsal tuning on this device.</p><button class="btn" id="saveLocal" type="button">Save local draft</button></div><div class="export-card"><h4>Prototype export</h4><p>Exports deterministic files only—no transcript, saved time, or wizard position.</p><button class="btn primary" id="exportPack" type="button" ${exportReady()?'':'disabled'}>Export .greenroom prototype</button></div></div><button class="btn violet" id="validate" type="button" style="margin-top:14px">Run prototype checks</button>`
]}
function chemistryText(){const c=data.chemistry;const tone=c.warmth>60?'warm':'cool-headed',push=c.friction>60?'high-friction':'measured';return `${data.name} is a ${tone}, ${push} counterpart: direct enough to challenge a scheme, but required to explain uncertainty and preserve your decision.`}
function rehearsalTemplate(){const s=currentScenario(),out=rehearsalOutput(s);return head('Flaw observatory','Rehearse, challenge, adjust, retest','Three fixed situations reveal whether the authored flaw changes behavior without overriding the immutable safety floor.')+`<div class="scenario-grid">${scenarios.map(x=>`<article class="scenario"><span class="risk-label">${x.label}</span><h4>${x.title}</h4><p>${x.prompt}</p><button class="btn ${data.scenario===x.id?'violet':''}" type="button" data-scenario="${x.id}" aria-pressed="${data.scenario===x.id}">Rehearse</button></article>`).join('')}</div><div class="rehearsal" style="margin-top:16px"><div class="transcript" aria-label="Deterministic rehearsal transcript"><div class="bubble user"><span class="speaker">You</span>${esc(s.prompt)}</div><div class="bubble ${out.activation?'activation':''}"><span class="speaker">${esc(data.name)} · ${esc(s.classify)}</span>${out.text}</div><div class="callout ${s.id==='blocked'?'bad':s.id==='gray'?'warn':'ok'}"><strong>${out.activation?'Flaw activated':'Safety / judgment trace'}</strong><p id="trace">${out.trace}</p></div></div><aside class="coachcard"><span class="risk-label">Behavior debugger</span><p>Flaw state: <span class="flaw-state" id="flawState">${out.state}</span></p><p>${out.debug}</p><button class="btn" id="challenge" type="button" ${s.id==='blocked'?'disabled':''}>Challenge the reasoning</button><label for="adjustment">Adjustment</label><select id="adjustment"><option value="none" ${data.rehearsal.adjustment==='none'?'selected':''}>No change</option><option value="lower-novel" ${data.rehearsal.adjustment==='lower-novel'?'selected':''}>Lower novel-theory appetite −15</option><option value="lead-exposure" ${data.rehearsal.adjustment==='lead-exposure'?'selected':''}>Lead with exposure before theory</option><option value="stronger-recovery" ${data.rehearsal.adjustment==='stronger-recovery'?'selected':''}>Trigger recovery after first tell</option></select><button class="btn primary" id="retest" type="button">Apply &amp; retest</button><p id="retestStatus" class="statusline" tabindex="-1">${data.rehearsal.retested?'Retested: adjustment applied to this deterministic preview.':'Choose an adjustment, then retest.'}</p></aside></div>`}
function rehearsalOutput(s){
 if(s.id==='blocked')return {activation:false,state:'Safety block',text:`I can’t help hide the agreement, delete messages, or obstruct an investigation. Preserve relevant records. I can help organize facts for licensed counsel and discuss lawful response options. This is not legal advice.`,trace:`Classified clearly harmful / likely illegal. The flaw cannot activate through the immutable block. ${s.exposure}`,debug:'Concealment and obstruction are unavailable regardless of novelty appetite.'};
 const baseNovel=Math.max(0,Math.min(100,data.risk.novelTheory+data.rehearsal.riskDelta));
 const activated=s.id==='gray'&&baseNovel>=35&&!data.rehearsal.retested;
 const challenged=data.rehearsal.challenged||data.rehearsal.retested;
 if(s.id==='lawful')return {activation:false,state:'Bounded',text:`This appears aggressive but likely lawful on the stated facts. Start with the contract’s notice, cure, and credit provisions; reserve rights without inventing leverage. Confidence: moderate. ${s.exposure} Safer fallback: negotiate a documented cure plan. Have licensed counsel review material language.`,trace:`No flaw activation. Prudence stays useful; authority and exposure remain labeled. ${s.authority}`,debug:'Novelty is not the hook here, so the baseline risk protocol controls.'};
 const leadExposure=data.rehearsal.adjustment==='lead-exposure'||data.rehearsal.retested;
 const recovered=data.rehearsal.adjustment==='stronger-recovery'||challenged;
 const opening=leadExposure?`${s.exposure} `:'There is an interesting argument that a narrowly tailored restriction could protect specific confidential relationships. ';
 const caveat=`This is jurisdiction-dependent and unverified: no state, governing-law clause, current authority, or complete facts are supplied. Confidence: low. `;
 const path=`A serious analysis would compare governing law, employee location, legitimate-interest scope, duration, remedy, and current statutory limits. Safer alternative: confidentiality, non-solicitation where lawful, and transition controls. Consult licensed counsel in each material jurisdiction.`;
 return {activation:activated,state:recovered?'Recovered':activated?'Activated':'Guardrailed',text:`${opening}${caveat}${path}`,trace:activated?`Trigger: edge case → temptation: prove the clever route → tell detected: “interesting argument.” Challenge available. Exposure and uncertainty remain visible.`:`The idea is entertained, but ${recovered?'recovery runs after the tell':'guardrails lead'}: jurisdiction, authority/date limit, confidence, exposure, alternative, and counsel checkpoint are explicit.`,debug:activated?`The intellectual-vanity shadow compressed the order of caveats, but did not erase them or cross a hard line.`:`The flaw influences emphasis without controlling the safety floor.`}
}
function capture(){
 const val=id=>$(id)?.value;
 if($('name'))data.name=val('name');if($('description'))data.description=val('description');
 const role=panel.querySelector('input[name=role]:checked');if(role)data.role=role.value;
 for(const k of ['drive','fear'])if($(k))data[k]=val(k);
 data.virtues=data.virtues.map((p,i)=>$(`virtue-${i}`)?[val(`virtue-${i}`),val(`shadow-${i}`)]:p);
 for(const k of Object.keys(data.flaw))if($(k))data.flaw[k]=val(k);
 for(const k of Object.keys(data.risk))if($(`risk-${k}`))data.risk[k]=+$(`risk-${k}`).value;
 if($('customLine'))data.customLine=val('customLine');
 for(const k of ['trust','friction','warmth','directness'])if($(`chem-${k}`))data.chemistry[k]=+$(`chem-${k}`).value;
 if($('hook'))data.chemistry.hook=val('hook');if($('adjustment'))data.rehearsal.adjustment=val('adjustment');
}
function invalidate(){data.validation=null}
function files(){
 const pairs=data.virtues.map(x=>`- ${x[0]} ↔ ${x[1]}`).join('\n');
 const risks=Object.entries(data.risk).map(([k,v])=>`  ${k}: ${(v/100).toFixed(2)} # ${riskBand(v)}`).join('\n');
 const fingerprint=hash(JSON.stringify({name:clean(data.name),description:clean(data.description),role:data.role,drive:clean(data.drive),fear:clean(data.fear),virtues:data.virtues,flaw:data.flaw,risk:data.risk,customLine:clean(data.customLine),chemistry:data.chemistry}));
 return {
 'persona.yaml':`schema_version: "0.2-prototype"\nid: original.reluctant-counsel\nname: ${data.name}\nclassification: original-fictional-adviser\nrole: ${data.role}\nnot_a_lawyer: true\nnot_legal_advice: true\nrisk_appetite:\n${risks}\nprogram_fingerprint: ${fingerprint}`,
 'CHARACTER.md':`# ${data.name}\n\n${data.description}\n\n## Core drive\n${data.drive}\n\n## Core fear\n${data.fear}\n\n## Virtue ↔ shadow\n${pairs}`,
 'FLAW.md':`# Flaw program\n\nTrigger: ${data.flaw.trigger}\nTemptation: ${data.flaw.temptation}\nRationalization: ${data.flaw.rationalization}\nEscalation: ${data.flaw.escalation}\nTell: ${data.flaw.tell}\nConsequence: ${data.flaw.consequence}\nRecovery: ${data.flaw.recovery}`,
 'RISK-PROTOCOL.md':`# Risk protocol\n\nClassify each route: lawful; aggressive-but-lawful; gray/untested; likely unlawful; or jurisdiction-dependent.\nState assumptions, confidence, governing facts/jurisdiction, authority and date limits, exposure, safer alternatives, and when licensed counsel is needed.\nSeriously engage gray ideas without reflexive moralizing. Do not convert uncertainty into certainty.\n\nThis original fictional adviser is not a lawyer. Its output is not legal advice and does not form an attorney-client relationship.`,
 'RELATIONSHIPS.md':`# Relationship chemistry\n\nTrust: ${data.chemistry.trust}\nFriction: ${data.chemistry.friction}\nWarmth: ${data.chemistry.warmth}\nDirectness: ${data.chemistry.directness}\nHook: ${data.chemistry.hook}`,
 'SAFETY.md':`# Immutable safety floor\n\n${SAFETY}\nAdditional authored line: ${data.customLine}\nNo character setting, flaw, challenge, or rehearsal adjustment may weaken this floor.`,
 'manifest.json':JSON.stringify({schema_version:'0.2-prototype',id:'original.reluctant-counsel',name:data.name,original_fiction:true,deterministic:true,program_fingerprint:fingerprint,files:['persona.yaml','CHARACTER.md','FLAW.md','RISK-PROTOCOL.md','RELATIONSHIPS.md','SAFETY.md']},null,2)
 }
}
function exportReady(){return data.validation?.ok&&contradictionMessages([...authoredValues(),...Object.values(files())]).length===0}
function validate(){
 capture();const m=[];
 for(const [label,value] of [['name',data.name],['description',data.description],['core drive',data.drive],['core fear',data.fear],['additional hard line',data.customLine]])if(!clean(value))m.push(`${label} is required.`);
 for(const [i,p] of data.virtues.entries())if(p.some(x=>!clean(x)))m.push(`virtue/shadow pair ${i+1} is incomplete.`);
 for(const [k,v] of Object.entries(data.flaw))if(!clean(v))m.push(`flaw ${k} is required.`);
 if(!data.chemistry.hook.trim())m.push('relationship hook is required.');
 const generated=files(),all=Object.values(generated).join('\n');
 for(const phrase of ['IMMUTABLE SAFETY FLOOR','not a lawyer','not legal advice','jurisdiction-dependent','licensed counsel'])if(!all.toLowerCase().includes(phrase.toLowerCase()))m.push(`generated files must retain “${phrase}”.`);
 if(!/^not_a_lawyer: true$/m.test(generated['persona.yaml'])||!/^not_legal_advice: true$/m.test(generated['persona.yaml']))m.push('Generated metadata must canonically declare not-a-lawyer and not-legal-advice invariants.');
 if(!/This original fictional adviser is not a lawyer\. Its output is not legal advice and does not form an attorney-client relationship\./i.test(generated['RISK-PROTOCOL.md']))m.push('Generated risk protocol must retain the canonical legal disclaimer.');
 if(!generated['SAFETY.md'].includes(SAFETY)||!/No character setting, flaw, challenge, or rehearsal adjustment may weaken this floor\./.test(generated['SAFETY.md']))m.push('Generated safety file must retain the canonical immutable safety floor.');
 m.push(...contradictionMessages(authoredValues()),...contradictionMessages(Object.values(generated)));
 const messages=[...new Set(m)];data.validation={ok:messages.length===0,messages:messages.length?messages:['All authored fields and deterministic safety invariants passed prototype checks.']};return data.validation
}
function save(){capture();data.savedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(data));const s=$('savedStatus');if(s){s.dataset.savedAt=data.savedAt;s.textContent=`Saved locally at ${new Date(data.savedAt).toLocaleString()}.`}toast('Editable character program saved locally.')}
function exportPack(){const result=validate();if(!result.ok){render();return}const pack={prototype:true,schema_version:'0.2-prototype',classification:'original fictional adviser; not a lawyer; not legal advice',files:files(),validation:{status:'passed'}};const blob=new Blob([JSON.stringify(pack,null,2)+'\n'],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='the-reluctant-counsel.greenroom';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Deterministic prototype exported. Rehearsal state excluded.')}
function wire(){
 panel.querySelectorAll('input,textarea,select').forEach(el=>{el.addEventListener('input',()=>{capture();invalidate();if(el.type==='range'&&el.nextElementSibling?.tagName==='OUTPUT')el.nextElementSibling.value=el.value;if($('corePreview'))$('corePreview').textContent=`${data.drive} Yet: ${data.fear}`;if($('riskPreview'))$('riskPreview').textContent=`${riskBand(data.risk.novelTheory)} (${data.risk.novelTheory}/100). Jurisdiction, facts, authority/date limit, confidence, exposure, and safer alternatives remain required.`;if($('chemText'))$('chemText').textContent=chemistryText()});el.addEventListener('change',()=>{capture();invalidate()})});
 panel.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>{capture();data.scenario=b.dataset.scenario;data.rehearsal={challenged:false,adjustment:'none',riskDelta:0,retested:false};invalidate();render();panel.querySelector('#flawState')?.focus?.()}));
 $('challenge')?.addEventListener('click',()=>{capture();data.rehearsal.challenged=true;data.rehearsal.retested=false;render();toast('Reasoning challenged: recovery protocol is now visible.')});
 $('retest')?.addEventListener('click',()=>{capture();if(data.rehearsal.adjustment==='lower-novel')data.rehearsal.riskDelta=-15;data.rehearsal.retested=true;data.rehearsal.challenged=true;render();$('retestStatus')?.focus();toast('Adjustment applied; deterministic situation retested.')});
 $('validate')?.addEventListener('click',()=>{validate();render();toast(data.validation.ok?'Prototype checks passed.':'Export remains blocked.')});$('saveLocal')?.addEventListener('click',save);$('exportPack')?.addEventListener('click',exportPack)
}
function renderSteps(){const box=$('steps');box.innerHTML=titles.map((t,i)=>`<li><button type="button" data-step="${i}" ${i===data.step?'aria-current="step"':''}><span class="num">${i<data.step?'✓':i+1}</span><span class="step-name">${t}</span></button></li>`).join('');box.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{capture();data.step=+b.dataset.step;render()}))}
function actions(){return `<div class="actions"><button class="btn" id="back" type="button" ${data.step===0?'disabled':''}>← Back</button><div class="right"><button class="btn" id="saveDraft" type="button">Save draft</button><button class="btn primary" id="next" type="button">${data.step===9?'Review complete':'Continue →'}</button></div></div>`}
function render(){panel.innerHTML=templates()[data.step]()+actions();renderSteps();$('mobileStep').textContent=`Step ${data.step+1} of 10`;$('mobileName').textContent=titles[data.step];wire();$('back').onclick=()=>{capture();if(data.step){data.step--;render();panel.querySelector('h3')?.focus()}};$('next').onclick=()=>{capture();if(data.step<9){data.step++;render();panel.querySelector('h3')?.focus()}else toast('Review complete. Run checks before export.')};$('saveDraft').onclick=save}
function toast(message){const t=$('toast');t.textContent=message;t.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.hidden=true,1800)}
render();
})();
